openapi: 3.1.0
info:
  version: 1.0.0
  title: my_app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: The contacts data base.
tags:
  - name: Contacts
    description: Operations with contacts
  - name: Auth
    description: Auth Operations
  - name: Sessions
    description: All about Sessions
servers:
  - url: http://localhost:3000
  - url: https://crud-app-5s4a.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
